version: '3.8'

services:
  fastapi-service:
    build: ./fastapi-service
    ports:
      - "3000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  nextjs-app:
    build: ./nextjs-app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
