version: '3.8'
services:
  fastapi-service:
    build: ./fastapi-service
    ports:
      - "3000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
  nextjs-app:
    build:
      context: ./nextjs-app
      args:
        - DATABASE_URL=${DATABASE_URL}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
        - GOOGLE_GEOCODING_API=${GOOGLE_GEOCODING_API}
        - MOONDREAM_API_KEY=${MOONDREAM_API_KEY}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
        - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
        - AWS_REGION=${AWS_REGION}
        - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - GOOGLE_GEOCODING_API=${GOOGLE_GEOCODING_API}
      - MOONDREAM_API_KEY=${MOONDREAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    restart: unless-stopped
