services:
  ml-service:
    build: ./ml-service # Using same Dockerfile for dev and prod
    command: uv run uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "9052:5000"
    volumes:
      - ./ml-service:/app
  nextjs-app:
    command: pnpm run dev --port 8000
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - GOOGLE_GEOCODING_API=${GOOGLE_GEOCODING_API}
      - MOONDREAM_API_KEY=${MOONDREAM_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
